/*
 * generated by Xtext
 */
package org.xtext.heapexplorer;

//import org.eclipse.xtext.scoping.IGlobalScopeProvider;
//import org.eclipse.xtext.scoping.impl.DefaultGlobalScopeProvider;
//import org.eclipse.xtext.scoping.impl.ImportUriGlobalScopeProvider;

/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
public class HeapExplorerRuntimeModule extends org.xtext.heapexplorer.AbstractHeapExplorerRuntimeModule {

	
//	public Class<? extends IGlobalScopeProvider> bindIGlobalScopeProvider() {
//		return DefaultGlobalScopeProvider.class;
//	}
	
}
