/*
* generated by Xtext
*/
package org.xtext.heapexplorer;

/**
 * Initialization support for running Xtext languages 
 * without equinox extension registry
 */
public class HeapExplorerStandaloneSetup extends HeapExplorerStandaloneSetupGenerated{

	public static void doSetup() {
		new HeapExplorerStandaloneSetup().createInjectorAndDoEMFRegistration();
	}
}

