/*
 * generated by Xtext
 */
package org.xtext.heapexplorer.ui;

import org.eclipse.ui.plugin.AbstractUIPlugin;

/**
 * Use this class to register components to be used within the IDE.
 */
public class HeapExplorerUiModule extends org.xtext.heapexplorer.ui.AbstractHeapExplorerUiModule {
	public HeapExplorerUiModule(AbstractUIPlugin plugin) {
		super(plugin);
	}
}
