/*
 * generated by Xtext
 */
package org.xtext.heapexplorer.ui.contentassist

import org.xtext.heapexplorer.ui.contentassist.AbstractHeapExplorerProposalProvider

/**
 * see http://www.eclipse.org/Xtext/documentation.html#contentAssist on how to customize content assistant
 */
class HeapExplorerProposalProvider extends AbstractHeapExplorerProposalProvider {
}
